new environment for simulation automation with cocotb and vcs
efabless/caravel pull request #139
Opened 2022-09-30 11:23 UTC by M0stafaRady

Adding the new environment for dynamic testing using cocotb and vcs the environment also can work with iverilog. 
For now it contain around 20 test that cover most of the features and working on adding more tests. 
The environment supports RTL and gatelevel simulation. It can also support SDF simulation when the sdf files included.

2022-10-02 08:49 UTC, marwaneltoukhy requested changes
- Please write what changed in the PR
- Please write what the directory structure should look like
- Please write what these scripts do
- Please change the name of `run.py` to be something more process specific
- We don't usually commit hex files, actually they should be added to the `.gitignore`, they should be generated automatically

P.S. When doing a big PR like this one you should be verbose in the PR description to help the reviewer understand what you are trying to do

2022-10-02 09:31 UTC, marwaneltoukhy requested changes

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/README.md
> +  >python3 run.py --test <test/s> -sim <type of simulation/s RTL GL or GL_SDF>  -tag <run tag optional>
I don't understand the difference

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/README.md
> +  >python3 run.py  --regression <regression> -tag <run tag optional>
I don't understand the difference

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/README.md
> +Navigate to the cocotb directory and run the following command
Where is the cocotb directory?

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/README.md
> +  >python3 run.py --test <test/s> -sim <type of simulation/s RTL GL or GL_SDF>  -tag <run tag optional>
where is the list of tests that I can run?

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/run.py
> +        os.environ["MCW_ROOT"] = f"{repo_path}/caravel_mgmt_soc_litex/"
Here you are assuming a specific directory structure, so either you write down what that structure is, and state that it's a dependency, or you do something to make sure that these files exist, or do something to start the setup (something like `make setup` in caravel_user_project)

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/run.py
> +        os.environ["MCW_ROOT"] = f"{repo_path}/caravel_mgmt_soc_litex/"
usually `caravel_mgmt_soc_litex` is renamed to `mgmt_core_wrapper`

2022-10-02 09:31 UTC, marwaneltoukhy commented on verilog/dv/cocotb/run.py
> +        os.environ["MCW_ROOT"] = f"{repo_path}/caravel_mgmt_soc_litex/"
There also should be an option to change the `MCW_ROOT` , so that if I type in the cmd `export MCW_ROOT=<dir path>` I can run it from wherever I want

2022-10-02 09:36 UTC, marwaneltoukhy commented
Please write if there are any dependencies, do I need to download cocotb? vsc? python3? iverilog? Docker? which versions?

2022-10-02 09:41 UTC, marwaneltoukhy commented
use `black` and `flake8` for formatting and linting your code

2022-10-02 13:53 UTC, M0stafaRady commented
Can you check the Pull request now ? I addressed all the comments

2022-10-09 14:50 UTC, marwaneltoukhy commented
What are the scripts: `caravel,py`, `caravel_tests.py`, `caravel_top.sv`, `common.py` and `cpu.py`?
I think you need to rename them and put them inside a directory if they are helper scripts.

2022-10-09 14:53 UTC, marwaneltoukhy commented
in `verify_cocotb.py` [This section](https://github.com/efabless/caravel/blob/d6f002cd70bc58e0836d2d4bc111e4781e9b0737/verilog/dv/cocotb/verify_cocotb.py#L315) Why are you exporting `MCW_ROOT` and `CARAVEL_ROOT`? you should be taking them from the environment

2022-10-09 14:55 UTC, marwaneltoukhy commented
I think we need a description, even if it is a small one of each test and what it does, and the full coverage until now.

2022-10-09 14:57 UTC, M0stafaRady commented
> What are the scripts: `caravel,py`, `caravel_tests.py`, `caravel_top.sv`, `common.py` and `cpu.py`?

these are not scripts these are part of cocotb testbench

2022-10-09 14:59 UTC, M0stafaRady commented
> in `verify_cocotb.py` [This section](https://github.com/efabless/caravel/blob/d6f002cd70bc58e0836d2d4bc111e4781e9b0737/verilog/dv/cocotb/verify_cocotb.py#L315) Why are you exporting `MCW_ROOT` and `CARAVEL_ROOT`? you should be taking them from the environment

I think it'd be better if the script can detect the environment itself as it would always have the same structure. for now the script isn't so mature but the plan is to make it independent of the environment to decrease the probability of simulating wrong netlist by mistake

2022-10-09 15:02 UTC, M0stafaRady commented
> I think we need a description, even if it is a small one of each test and what it does, and the full coverage until now.

[test.json ](https://github.com/efabless/caravel/blob/cocotb/verilog/dv/cocotb/tests.json) has a small description of each test. You can get the coverage by running regressions

2022-10-09 15:42 UTC, marwaneltoukhy commented
> > What are the scripts: `caravel,py`, `caravel_tests.py`, `caravel_top.sv`, `common.py` and `cpu.py`?
> 
> these are not scripts these are part of cocotb testbench

Then put it in a new directory, they shouldn't be left there with no explanation

2022-10-09 15:43 UTC, marwaneltoukhy commented
> > in `verify_cocotb.py` [This section](https://github.com/efabless/caravel/blob/d6f002cd70bc58e0836d2d4bc111e4781e9b0737/verilog/dv/cocotb/verify_cocotb.py#L315) Why are you exporting `MCW_ROOT` and `CARAVEL_ROOT`? you should be taking them from the environment
> 
> I think it'd be better if the script can detect the environment itself as it would always have the same structure. for now the script isn't so mature but the plan is to make it independent of the environment to decrease the probability of simulating wrong netlist by mistake

Our whole flow uses `CARAVEL_ROOT` and `MCW_ROOT` so this script should be aligned with the rest of the flow

2022-10-09 15:44 UTC, marwaneltoukhy commented
> > I think we need a description, even if it is a small one of each test and what it does, and the full coverage until now.
> 
> [test.json ](https://github.com/efabless/caravel/blob/cocotb/verilog/dv/cocotb/tests.json) has a small description of each test. You can get the coverage by running regressions

We need a human readable description, and the coverage as well.

2022-10-10 11:59 UTC, M0stafaRady commented
> > > What are the scripts: `caravel,py`, `caravel_tests.py`, `caravel_top.sv`, `common.py` and `cpu.py`?
> > 
> > 
> > these are not scripts these are part of cocotb testbench
> 
> Then put it in a new directory, they shouldn't be left there with no explanation

done

2022-10-10 11:59 UTC, M0stafaRady commented
> > > in `verify_cocotb.py` [This section](https://github.com/efabless/caravel/blob/d6f002cd70bc58e0836d2d4bc111e4781e9b0737/verilog/dv/cocotb/verify_cocotb.py#L315) Why are you exporting `MCW_ROOT` and `CARAVEL_ROOT`? you should be taking them from the environment
> > 
> > 
> > I think it'd be better if the script can detect the environment itself as it would always have the same structure. for now the script isn't so mature but the plan is to make it independent of the environment to decrease the probability of simulating wrong netlist by mistake
> 
> Our whole flow uses `CARAVEL_ROOT` and `MCW_ROOT` so this script should be aligned with the rest of the flow

done

2022-10-11 07:28 UTC, marwaneltoukhy commented
This looks fine and works fine for me.

2022-10-11 08:41 UTC, merged