Modifications to the openframe padframe
efabless/caravel pull request #503
Opened 2023-09-25 23:36 UTC by RTimothyEdwards

Modified the openframe padframe so that the GPIO "wrapped" cells are replaced with the base cells.  Routing to pins is instead done in the "gpio_connects" cells while improving on the original routing (fewer cross-overs, multiple vias per contact, wider buses for the analog signals).  Made small adjustments to many of the openframe wrapper pins to keep them all on a 10nm grid.  Moved the connections previously from the "wrapped" GPIO cell back from the openframe project border, so that the border can be clear of all blockages.  Added the DEF file of the wrapper (previously only in the openframe example repo) to the def/ directory.  Note:  The modified LVS scripts depend on the gate-level netlists of the frame, which have been committed in a prior pull request.  This pull request does not conflict with those files.

2023-09-25 23:45 UTC, RTimothyEdwards commented
For the record, this pull request should resolve the outstanding issues with geometry not belonging to pins extending into the user project area.  Also the abutment bounding box is terminated at the ends of the pins and does not extend into the bounding boxes of the padframe or constant_block cells, but abuts cleanly.

2023-09-26 09:18 UTC, marwaneltoukhy requested changes

2023-09-26 09:18 UTC, marwaneltoukhy commented on mag/openframe_project_wrapper.mag
There are weird metals coming out of the pins, are these intentional?
![image](https://github.com/efabless/caravel/assets/67271180/6ee0d5f3-d504-4d0f-a24a-c507a643a785)

2023-09-26 09:18 UTC, marwaneltoukhy commented on def/openframe_project_wrapper.def
There are extra metals in the def as well, also the overlap of the pin with the PR boundary is less than a metal track, which will cause issues when routing using openroad
![image](https://github.com/efabless/caravel/assets/67271180/e99b6f47-62b2-4c4f-96c4-c474894641b4)

2023-09-26 09:23 UTC, marwaneltoukhy commented on mag/openframe_project_wrapper.mag
Also, the overlaps we see in the def between the pins and the PR boundary isn't in the mag.

2023-09-26 12:53 UTC, RTimothyEdwards commented on def/openframe_project_wrapper.def
I will need to check the TAPERRULE definition.  The DEF read routine is interpreting such rules as not having wire extensions, but clearly klayout is reading the wires as having wire extensions.  I can rewrite the DEF file without the nets (pins only) which is the quickest way to get rid of them.

2023-09-26 12:55 UTC, RTimothyEdwards commented on mag/openframe_project_wrapper.mag
Yes, they're intentional to indicate all the routing from the boundary out to the extent of geometry, although I should probably just make sure that all pins just extend back to the same boundary position.  That's a bit of a pain but I can probably get it done today.

2023-09-26 12:56 UTC, RTimothyEdwards commented on def/openframe_project_wrapper.def
If I change the wrapper definition as I mentioned above in the response to your previous comment, then there won't be any need for anything in the wrapper DEF except pins.

2023-09-26 13:00 UTC, RTimothyEdwards commented on def/openframe_project_wrapper.def
But yes, I'm actually right about the wire extension, and klayout is wrong.  The NONDEFAULTRULE layers have a WIREEXT which defaults to zero.  So klayout is incorrect in drawing wire extensions above and below the pin.  Assuming that OpenROAD has a correct understanding of the nondefault rules, then it should not have a problem with the geometry.  The klayout developers should be alerted to the error.

2023-09-26 13:05 UTC, marwaneltoukhy commented on def/openframe_project_wrapper.def
I'll try it out with openroad, but still we need the pins extended inside the PR boundary so that openroad can route to there pins, if it's just abbuted to the PR boundary it won't be able to read it. I think the recommended extension would be 1um inside the boundary

2023-09-26 13:08 UTC, marwaneltoukhy commented on mag/openframe_project_wrapper.mag
This would cause issues in the XOR check in precheck, I think we don't ever use the empty wrapper gds except as a golden wrapper for precheck to do XOR on. I am creating the golden wrapper from the mag you're providing, to be exactly the same as the template def.

2023-09-26 15:00 UTC, RTimothyEdwards commented on def/openframe_project_wrapper.def
I was under the impression from a previous live discussion that it would be okay for the pins to be on the PR boundary.  I suppose that was supposed to mean that the pins should be _inside_ and on the boundary.  Since it appears that OpenROAD doesn't care if the PR boundary overlaps other cells (since the user project area is placed manually, not automatically) then I will go back to having the PR boundary where it was before.

2023-09-26 16:53 UTC, RTimothyEdwards commented
@marwaneltoukhy :  All issues should now be resolved except that there will be an overlap of the PR boundary between the user project wrapper and the padframe.  I believe that this will not be a problem.

2023-09-26 20:54 UTC, RTimothyEdwards commented on def/openframe_project_wrapper.def
I created an issue for klayout and in the ensuing discussion it was determined that the default WIREEXT value was changed between LEF/DEF spec 5.7 and 5.8 without a thought to backwards compatibility.  Ultimately two issues were found in klayout (1) generating a default wire extension for non-default rule wires under version 5.7, and (2) generating a wire extension of 1/2 wire width regardless of the WIREEXT value given.  Fortunately, the way I have the openframe wrapper layout now, I don't need any nets represented, and can restrict the wrapper DEF file to just pins, and avoid all those issues.

2023-09-27 11:14 UTC, marwaneltoukhy commented
@RTimothyEdwards we need to increase the PR Boundary by `0.02um` in the X direction, to respect the minimum width of metal 3. openroad routes outside the PR boundary when the Pin doesn't respect the minimum width, I created an issue here https://github.com/The-OpenROAD-Project/OpenLane/issues/2006

2023-09-27 11:59 UTC, marwaneltoukhy commented
@RTimothyEdwards I manually stretched the pins inside the PR boundary by `0.02um` in the def file, and tried the flow with it, and it fixed the issue, maybe we can stretch it a bit more just to be safe.

2023-09-27 12:57 UTC, RTimothyEdwards commented
@marwaneltoukhy :  The end result of the conversation over klayout is that the wire extension applies only to the extension at a via, and not for any arbitrary wire segment, so klayout's interpretation is correct, and I need to rework the code in magic to assume a default wire extension of 1/2 route width.

2023-09-27 18:20 UTC, RTimothyEdwards commented
@marwaneltoukhy :  If there is no problem routing to the metal2 pins on top and bottom but there is on the pins to the right and left, then that means that the router wants to see at least the minimum metal width available inside the PR boundary.  Since the metal3 minimum with is 0.3um and the pin is sticking out by 0.28um, then it is short by 0.02um, so the 0.02um is sufficient and there should be no need to extend them further.

I will extend the pins and make what I hope is the last commit.

2023-09-27 19:11 UTC, RTimothyEdwards commented
@marwaneltoukhy :  I just made one additional commit to move all metal3 pins 0.02um further into the user project area so that the minimum length exposed is equal to the minimum metal width rule.  This should be the same as what you did to test that the routing works.  Please verify the solution.

2023-10-01 08:00 UTC, marwaneltoukhy commented
@RTimothyEdwards The DEF file looks good, I took it through openlane and verified that there are no issues.

There's another issue that I just found, there are no pins in the empty wrapper mag for this power pad, I know that there's another power pad for `VSSD1` and `VCCD1`, but shouldn't they all have pins in the wrapper?

![image](https://github.com/efabless/caravel/assets/67271180/370db284-160c-41cb-8a71-a3ede06260ef)

2023-10-02 00:55 UTC, RTimothyEdwards commented
Yes, they should, and let me do one more set of fixes.

2023-10-02 01:18 UTC, RTimothyEdwards commented
@marwaneltoukhy :  Okay, the missing power pins have been added to the wrapper layout, and I regenerated the DEF (and copied it to the openframe project example repository).

2023-10-08 11:06 UTC, marwaneltoukhy commented
I added the empty project wrapper gds file for precheck's XOR

2023-10-08 11:06 UTC, marwaneltoukhy approved these changes

2023-10-08 20:39 UTC, RTimothyEdwards commented
@marwaneltoukhy , @jeffdi :  Per today's discussion at Efabless, I realized that one cell that has been modified for openframe, `chip_io_gpio_connects`, is shared with both caravel and caravan and must not be changed.  I will need to fix this by copying the modified cell to a new name to be used by openframe while restoring the original contents of the cell.  I should be able to make that update today or tomorrow.

2023-10-08 22:04 UTC, RTimothyEdwards commented
The issue I mentioned above has now been fixed.  The original `chip_io_gpio_connects.mag` layout for caravel and caravan has been restored, and the one modified for openframe has been renamed `chip_io_gpio_connects_vert.mag` so that it will not conflict.

2023-10-17 10:55 UTC, marwaneltoukhy requested changes
@RTimothyEdwards Just realized that `verilog/rtl/__openframe_project_wrapper.v` doesn't have the `vssio` and `vddio` power pins, these are needed to pass precheck.

2023-10-18 16:50 UTC, RTimothyEdwards commented
@marwaneltoukhy :  `vddio` and `vssio` pins added to RTL and GL netlists.

2023-10-19 07:10 UTC, marwaneltoukhy approved these changes

2023-10-19 15:02 UTC, jeffdi approved these changes

2023-10-19 15:02 UTC, merged