Changes that correct gpio_default_block, user_id_programming, and mgmt_core references.
efabless/caravel pull request #73
Opened 2022-04-18 09:04 UTC by d-m-bailey

mgmt_core_wrapper: fixes #71 
- Use absolute path instead of relative path.

user_id_programming: fixes #70 
- Remove GDS references as GDS is no longer modified.
- Corrected string concatenation.
- Corrected mag data replacement.
- Corrected verilog data replacement.

gpio_default_block: fixes #72 
- Rename instances for gpio_default_blocks 0-4 in caravel.mag and caravan.mag.
- Change replace range in gen_gpio_defaults.py to handle gpio_default_blocks 0-4.

2022-04-18 14:13 UTC, RTimothyEdwards reviewed
Some fixes have already been made in another pull request, so these changes will have to be reviewed individually and merged by cherry-picking.

2022-04-18 22:23 UTC, d-m-bailey commented
I'll revert the `gpio_default_block` changes.

2022-04-18 23:43 UTC, RTimothyEdwards commented
Thanks.  I made a quick pass over the rest and they look good, but I'm doing a few fixes to Caravan and I'll try to get your pull request reviewed and queued up for a merge next.

2022-04-19 00:55 UTC, RTimothyEdwards requested changes
Makefile lines 125 and 177:  I agree that the path should not be relative, which makes it depend on the management core wrapper being cloned into or linked from caravel, but it should be `$(MCW_ROOT)`, which is the path to the management core wrapper repository, not `$(UPRJ_ROOT)`, which is the user project repository.

2022-04-19 00:56 UTC, RTimothyEdwards commented
@d-m-bailey :  If you can make that one correction, I can go ahead and approve this for a merge, because there are no conflicts with the pull request I'm currently working on.

2022-04-19 01:43 UTC, RTimothyEdwards approved these changes
Looks good to me.

2022-04-19 01:43 UTC, RTimothyEdwards commented
@jeffdi :  Please merge this pull request.

2022-04-19 02:03 UTC, d-m-bailey commented
@RTimothyEdwards Changed `UPRJ_ROOT/mgmt_core_wrapper` to `MCW_ROOT` for `mgmt_core_wrapper` gds path.

There's also an (apparently) unused `MGMT_AREA_ROOT` variable in a couple makefiles.

2022-04-19 02:33 UTC, d-m-bailey commented
@jeffdi @RTimothyEdwards Can you wait on this?

It's not only moving the licon, but also the met1 and via at the same locations!

<img width="1178" alt="user_id_programming_no_via" src="https://user-images.githubusercontent.com/8349634/163908653-e7987e89-272c-44da-a443-c9a644bde0ed.png">

2022-04-19 03:15 UTC, RTimothyEdwards commented
@jeffdi :  Mitch is right;  the original reason for using the GDS was that it was a bit simpler to alter the contacts, since in magic the contact can't just be moved;  it has to be replaced by the overlapping metals or else it will leave empty space behind.  @d-m-bailey :  I understand the issue and I just need to make a modification to the .mag file to ensure that there is redundant metal over the area of the via in the file so that when the via is moved, the metal will remain.  I suggest that @jeffdi go ahead and merge the pull request anyway, and I will fix the .mag file early tomorrow.

2022-04-19 03:24 UTC, merged

2022-04-19 03:24 UTC, jeffdi commented
done.

-- Jeff


On Mon, Apr 18, 2022 at 8:15 PM R. Timothy Edwards ***@***.***>
wrote:

> @jeffdi <https://github.com/jeffdi> : Mitch is right; the original reason
> for using the GDS was that it was a bit simpler to alter the contacts,
> since in magic the contact can't just be moved; it has to be replaced by
> the overlapping metals or else it will leave empty space behind.
> @d-m-bailey <https://github.com/d-m-bailey> : I understand the issue and
> I just need to make a modification to the .mag file to ensure that there is
> redundant metal over the area of the via in the file so that when the via
> is moved, the metal will remain. I suggest that @jeffdi
> <https://github.com/jeffdi> go ahead and merge the pull request anyway,
> and I will fix the .mag file early tomorrow.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/efabless/caravel/pull/73#issuecomment-1101950738>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKAZZ5JXS4OCNQ3DVVEP5BTVFYQN3ANCNFSM5TVLXVLA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-19 07:18 UTC, d-m-bailey commented
@RTimothyEdwards Currently, `scripts/set_user_id.py` does a global replace on the coordinates of the `viali`s. Unfortunately, also moves `via1` and other shapes at the exact same location. I tried replacing just the first instance and that fixed some of the problems, but not where there is only `viali` (as you mentioned).

2022-04-19 07:33 UTC, d-m-bailey commented
@RTimothyEdwards Looks like the global replace of coordinates moved `via1` also, but since there was no `metal2`, the `via1` disappears. Here's the results of replacing only the first occurrence of the target coordinate. Missing metal drops from 14 to 8. Attempting to fix by adding `metal1` programatically. 
<img width="1221" alt="user_id_partial_fix" src="https://user-images.githubusercontent.com/8349634/163949751-dfb7dc93-d2ec-427d-9207-28d718a98e40.png">